services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: quillqueue
      POSTGRES_USER: quill
      POSTGRES_PASSWORD: quill
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
