spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/quillqueue
    username: quill
    password: quill
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
logging:
  level:
    root: INFO
management:
  endpoints:
    web:
      exposure:
        include: health,info
